### ISSUE TITLE
Messages are not loading for new users if user not allowed for notification permission

### ISSUE THREAD

**Issue by raviteja11b** [AppLozic/Applozic-iOS-SDK#470] opened 2018-05-07 07:54 UTC
Hi, I am using applozic in my iOS app, When a user signup in my app we will send him a message trough Applozic admin API's.
this works fine if the user allows permission for push notifications.

If user don't allow permission for push notifications and signup in my app, the messages are not loading in applozic chat.
I have went inside the chat list page and refreshed but still, it shows no chats available until I restart my app or logout and login.

To Reproduce
-> signup with new number without allowing notification permission
-> Send a message from different number by keeping the app open OR send a message to that number by using admin API
-> It suppose to receive message because the SDK uses socket connection
-> Go to list of chats screen and refresh the page you will not be able to see the meesages

**Comment by mhrpatel12** [comment] 2018-05-07 15:12
Hi @raviteja11b 
We'll look into this.
Did you tried to reproduce this in our Sample Application?

**Comment by mukeshthawani** [comment] 2018-05-30 05:59
We tried it in the latest version but we were not able to reproduce this. 

Closing this, feel free to open this issue with more details.

**Closed by mukeshthawani** 2018-05-30 05:59 UTC
Labels: question
