### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by samarth4487** [AppLozic/Applozic-iOS-SDK#534] opened 2019-11-13 03:28 UTC
App is crashing as soon as the app is opened. Here are the logs and stack trace.
SDK Version: 6.10.0
Xcode: 10.2

<img width="1235" alt="Screenshot 2019-11-13 at 8 55 11 AM" src="https://user-images.githubusercontent.com/9333399/68730657-618c5500-05f3-11ea-88ac-7d199d0eb29c.png">

Stacktrace:

2019-11-13 08:48:42.264987+0530 Cityflo[1446:16768] <ALAPIResponse.m:25> self.generatedAt : 1573615122110
2019-11-13 08:48:42.265151+0530 Cityflo[1446:16768] <ALAPIResponse.m:26> self.status : success
2019-11-13 08:48:42.265407+0530 Cityflo[1446:16768] -[NSTaggedPointerString objectForKeyedSubscript:]: unrecognized selector sent to instance 0xdcfd442b8049cdfd
2019-11-13 08:48:42.269228+0530 Cityflo[1446:16768] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString objectForKeyedSubscript:]: unrecognized selector sent to instance 0xdcfd442b8049cdfd'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c4896fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ba2dac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c4a7ab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010c48e443 ___forwarding___ + 1443
	4   CoreFoundation                      0x000000010c490238 _CF_forwarding_prep_0 + 120
	5   Applozic                            0x000000010524b87d -[ALChannel parseMessage:] + 109
	6   Applozic                            0x000000010524b7d2 -[ALChannel initWithDictonary:] + 82
	7   Applozic                            0x000000010527ec4a -[ALChannelSyncResponse initWithJSONString:] + 730
	8   Applozic                            0x0000000105254ddf __59+[ALChannelClientService syncCallForChannel:andCompletion:]_block_invoke + 1103
	9   Applozic                            0x00000001053d20e0 __65+[ALResponseHandler processRequest:andTag:WithCompletionHandler:]_block_invoke_3.173 + 48
	10  libdispatch.dylib                   0x000000010d84cd7f _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010d84ddb5 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010d85b080 _dispatch_main_queue_callback_4CF + 1540
	13  CoreFoundation                      0x000000010c3f08a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x000000010c3eaf56 __CFRunLoopRun + 2310
	15  CoreFoundation                      0x000000010c3ea302 CFRunLoopRunSpecific + 626
	16  GraphicsServices                    0x000000010f1af2fe GSEventRunModal + 65
	17  UIKitCore                           0x0000000114aa0ba2 UIApplicationMain + 140
	18  Cityflo                             0x0000000102faa8fb main + 75
	19  libdyld.dylib                       0x000000010d8c2541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by samarth4487** [comment] 2019-11-13 06:49
-(void)parseMessage:(id) messageJson

This is where the crash is happening!

**Comment by arthurchambsp** [comment] 2019-11-13 07:57
Same issue here.

**Comment by reytum** [comment] 2019-11-13 08:30
@samarth4487 @arthurchambsp We have identified the issue. The team is looking into it on priority. This will be fixed soon.

**Comment by samarth4487** [comment] 2019-11-13 08:34
@reytum App is crashing for each and every user. It'd be great if you can solve it ASAP.

**Comment by reytum** [comment] 2019-11-13 08:37
@samarth4487 We are deploying the new changes, it will be done within next 30 mins.

**Comment by reytum** [comment] 2019-11-13 09:08
@samarth4487 @arthurchambsp The issue is fixed. Can you check now.

**Comment by ravirajw** [comment] 2019-11-14 09:52
@reytum Does 6.17.1 has this fix in it?

**Comment by samarth4487** [comment] 2019-11-14 10:02
@ravirajw I'm using 6.10.0 so basically every build after that has a fix for this issue.

**Comment by ravirajw** [comment] 2019-11-14 10:09
@samarth4487 Ok Thanks. My app has 6.8. So I guess I need to update it.

**Closed** 2020-02-19 06:50 UTC
