### ISSUE TITLE
/Applozic/Applozic.framework/en.lproj: File exists Issue.

### ISSUE THREAD

**Issue by pradz39** [AppLozic/Applozic-iOS-SDK#338] opened 2017-02-03 06:08 UTC
Hi I have integrated applozic using cocoa pods, it took 3.8.1 version. I am always getting compiler error like "/Applozic/Applozic.framework/en.lproj: File exists Issue." This is happening because of multiple en.lproj file in the Applozic project. If I remove duplicate en.lproj file in Applozic then it compiles fine. Can you please check this.

**Comment by Abhishek9634** [comment] 2017-02-03 06:21
@pradz39 : Can you show me the duplicate folders i.e. Screenshot.

**Comment by pradz39** [comment] 2017-02-03 06:26
![screen shot 2017-02-03 at 11 54 03 am](https://cloud.githubusercontent.com/assets/5805896/22581643/b1fa3bc0-ea07-11e6-8d30-90f52c0856e1.png)

Hi Abhishek, PFA screenshot of the issue I mentioned. I am using xcode 8.2.1.

**Comment by Abhishek9634** [comment] 2017-02-03 06:30
@pradz39 :  Thanks a lot and which folder(s) you have deleted ? 
As there are 3 folders from top
1. en.proj -> localizable.strings
2. en.proj -> localizable.strings
3. en.proj -> Main.strings

**Comment by pradz39** [comment] 2017-02-03 06:33
@Abhishek9634  I copied the values of Main.strings(2nd) and localizable.strings(3rd) to localizable.strings(1st) and deleted 2 and 3rd. Also I did the same for hu.lproj.

**Comment by Abhishek9634** [comment] 2017-02-03 06:35
@pradz39 : Thanks for informing me. In the next release i will surely do this changes :)

**Comment by pradz39** [comment] 2017-02-03 06:40
Okay thank you @Abhishek9634.

**Comment by jlubeck** [comment] 2017-03-10 21:25
This is still an issue on 3.8.4 which was released just a few days ago. We can't archive and submit to app store because of this. Any idea when it will be fixed?
Thanks!!!

**Comment by manjunathgudisi** [comment] 2017-04-20 05:35
I have the same issue though Im using Applozic (3.8.6) version. Any suggestions how to resolve this error.

**Comment by mickbyrne** [comment] 2017-06-18 00:23
We're having the same issue. It's impossible to create archive of projects that include AppLozic. This is a major, major flaw and is creating a lot of frustration amongst our developers that we've included this framework in our project. Please prioritise.

**Comment by mukeshthawani** [comment] 2017-06-19 11:20
Can you please try our sample cocoapods project: https://github.com/AppLozic/Applozic-iOS-Chat-Samples/tree/master/ApplozicCocoaPodDemo

See if you can reproduce the issue there. If you can reproduce the issue then share that sample project at support@applozic.com

**Comment by fabiofaibtw** [comment] 2017-06-27 08:37
I figure out the issue.  If Podfile used use_frameworks!, then the issue will come out.  If comment use_frameworks!, issue will be solved.

However, my problem is some of the frameworks must need to enable use_frameworks!.  Is there any suggestion to fix this?

**Comment by mukeshthawani** [comment] 2017-06-27 08:41
@fabiofaibtw We will release a new version in a day or two that should fix this problem. Once that's fixed then you don't have to comment user_frameworks!

For now, you can copy the content of one localizable.string to other and delete the duplicate in applozic framework.

**Comment by mukeshthawani** [comment] 2017-07-06 14:21
Fixed in 3.9.1

**Closed by mukeshthawani** 2017-07-06 14:21 UTC
